import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next dom for pm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <p>  <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={1172} height={1116} />
          </span></p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.pascal-moreno.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={172} height={116} />
          </span>
        </a>
      </footer>
    </div>
  )
}
